import {StyleSheet, Dimensions} from 'react-native';
import {primaryColor} from '../../../res/strings/eng';

export const createStyles = (isDark: boolean) =>
  StyleSheet.create({
    modalContainer: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: isDark
        ? 'rgba(0, 0, 0, 0.95)'
        : 'rgba(255, 255, 255, 0.95)',
    },
    modalContent: {
      height: '90%',
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      overflow: 'hidden',
      backgroundColor: isDark ? '#1a1a1a' : 'white',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? '#333' : '#e0e0e0',
      backgroundColor: isDark ? '#1a1a1a' : 'white',
    },
    closeButton: {
      padding: 4,
      opacity: 0.8,
    },
    headerText: {
      fontSize: 18,
      fontWeight: '600',
      color: isDark ? 'white' : 'black',
    },
    placeholder: {
      width: 28,
    },
    commentsContainer: {
      flex: 1,
      paddingHorizontal: 16,
      backgroundColor: isDark ? '#1a1a1a' : 'white',
    },
      commentItem: {
      flexDirection: 'row',
      marginVertical: 12,
      alignItems: 'flex-start',
      backgroundColor: isDark ? '#1a1a1a' : 'white',
      borderRadius: 8,
      padding: 8,
    },
    replyItem: {
      marginLeft: 40,
      paddingLeft: 12,
      borderLeftWidth: 1,
      borderLeftColor: isDark ? '#333' : '#e0e0e0',
      backgroundColor: isDark ? '#1a1a1a' : 'white',
    },
    commentAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      marginRight: 12,
      borderWidth: 1,
      borderColor: isDark ? '#333' : '#e0e0e0',
    },
    commentContent: {
      flex: 1,
      marginRight: 8,
    },
    commentHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    commentUsername: {
      fontWeight: '600',
      fontSize: 14,
      color: isDark ? 'white' : 'black',
    },
    commentText: {
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 4,
      color: isDark ? '#e0e0e0' : '#2c2c2c',
    },
    commentMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
    },
    commentTimestamp: {
      fontSize: 12,
      marginRight: 16,
      color: isDark ? '#8e8e8e' : '#666666',
    },
    commentLikes: {
      fontSize: 12,
      marginRight: 16,
      color: isDark ? '#8e8e8e' : '#666666',
    },
    replyButton: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      backgroundColor: isDark ? '#1a9cd8' : '#3EB9F1',
    },
    replyButtonDisabled: {
      backgroundColor: isDark ? '#404040' : '#ccc',
      opacity: 0.7,
    },
    replyButtonText: {
      color: 'white',
      fontWeight: '600',
      fontSize: 13,
    },
    replyInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderTopWidth: 1,
      borderTopColor: isDark ? '#333' : '#e0e0e0',
      backgroundColor: isDark ? '#1a1a1a' : 'white',
    },
    replyInput: {
      flex: 1,
      marginRight: 8,
      padding: 8,
      borderRadius: 20,
      backgroundColor: isDark ? '#2a2a2a' : '#f0f0f0',
      color: isDark ? 'white' : 'black',
      borderWidth: 1,
      borderColor: isDark ? '#404040' : '#e0e0e0',
    },
    likeButton: {
      padding: 4,
      borderRadius: 12,
      backgroundColor: isDark ? '#2a2a2a' : '#f5f5f5',
    },
    editContainer: {
      marginTop: 4,
      backgroundColor: isDark ? '#2a2a2a' : '#f5f5f5',
      borderRadius: 8,
      padding: 8,
    },
    editInput: {
      borderRadius: 8,
      padding: 8,
      minHeight: 40,
      marginBottom: 8,
      backgroundColor: isDark ? '#1a1a1a' : 'white',
      color: isDark ? 'white' : 'black',
      borderWidth: 1,
      borderColor: isDark ? '#404040' : '#e0e0e0',
    },
    editActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: 8,
    },
    editButton: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      marginLeft: 8,
      backgroundColor: isDark ? '#2a2a2a' : '#f5f5f5',
      borderWidth: 1,
      borderColor: isDark ? '#404040' : '#e0e0e0',
    },
    saveButton: {
      backgroundColor: isDark ? '#1a9cd8' : '#3EB9F1',
      borderWidth: 0,
    },
    editButtonText: {
      color: isDark ? '#8e8e8e' : '#666666',
      fontWeight: '500',
    },
    saveButtonText: {
      color: 'white',
      fontWeight: '600',
    },
    commentInputContainer: {
      padding: 12,
      borderTopWidth: 1,
      borderTopColor: isDark ? '#333' : '#e0e0e0',
      backgroundColor: isDark ? '#1a1a1a' : 'white',
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? '#2a2a2a' : '#f5f5f5',
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      marginTop: 8,
      borderWidth: 1,
      borderColor: isDark ? '#404040' : '#e0e0e0',
    },
    commentInput: {
      flex: 1,
      fontSize: 14,
      color: isDark ? 'white' : 'black',
      minHeight: 36,
      maxHeight: 100,
      paddingTop: 8,
      paddingBottom: 8,
      marginRight: 8,
    },
    postButton: {
      padding: 8,
      backgroundColor: isDark ? '#1a9cd8' : '#3EB9F1',
      borderRadius:20,
      opacity: 1,
      justifyContent: 'center',
      alignItems: 'center',
      width: 36,
      height: 36,
    },
    disabledPostButton: {
      opacity: 0.5,
      backgroundColor: isDark ? '#404040' : '#ccc',
    },
    replyingToContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 16,
      backgroundColor: isDark ? '#2a2a2a' : '#f5f5f5',
      borderRadius: 12,
      marginBottom: 8,
      marginHorizontal: 12,
      borderWidth: 1,
      borderColor: isDark ? '#404040' : '#e0e0e0',
    },
    replyingToText: {
      fontSize: 14,
      fontWeight: '500',
      color: isDark ? '#8e8e8e' : '#666666',
    },
    replyContainer: {
      marginLeft: 40,
      paddingLeft: 12,
      borderLeftWidth: 1,
      borderLeftColor: isDark ? '#333' : '#e0e0e0',
      backgroundColor: isDark ? '#1a1a1a' : 'white',
    },
    replyHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
    },
    replyAvatar: {
      width: 24,
      height: 24,
      borderRadius: 12,
      marginRight: 8,
      borderWidth: 1,
      borderColor: isDark ? '#333' : '#e0e0e0',
    },
    replyUsername: {
      fontWeight: '600',
      fontSize: 13,
      color: isDark ? 'white' : 'black',
    },
    replyText: {
      fontSize: 13,
      lineHeight: 18,
      color: isDark ? '#e0e0e0' : '#2c2c2c',
    },
    replyMeta: {
      flexDirection: 'row',
      marginTop: 4,
      alignItems: 'center',
    },
    replyTimestamp: {
      fontSize: 12,
      marginRight: 12,
      color: isDark ? '#8e8e8e' : '#666666',
    },
    replyLikes: {
      fontSize: 12,
      color: isDark ? '#8e8e8e' : '#666666',
    },
    optionsButton: {
      padding: 4,
      borderRadius: 12,
      backgroundColor: isDark ? '#2a2a2a' : '#f5f5f5',
    },
    optionsModalOverlay: {
      flex: 1,
      backgroundColor: isDark ? 'rgba(0, 0, 0, 0.7)' : 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    optionsModalContent: {
      width: '80%',
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: isDark ? '#2a2a2a' : 'white',
      borderWidth: 1,
      borderColor: isDark ? '#404040' : '#e0e0e0',
    },
    optionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 15,
      paddingHorizontal: 20,
      borderBottomWidth: 0.5,
      borderBottomColor: isDark ? '#404040' : '#CCCCCC',
      backgroundColor: isDark ? '#2a2a2a' : 'white',
    },
    optionText: {
      marginLeft: 15,
      fontSize: 16,
      color: isDark ? 'white' : 'black',
      fontWeight: '500',
    },
    dangerOption: {
      color: '#FF3B30',
    },
  });
