export const navigationDrawerOptions = [
  'Room',
  'Tasks',
  'Insights',
  'Generate QR',
  'Feed News',
  'Events & Hackathons',
  'Rewards',
  'Saved',
  'Help and FAQs',
  'Contact us ',
  'Invite',
  'Setting',
  'About',
];
