// Re-export all constants
export {
  MAX_CONNECTION_ATTEMPTS,
  isSmallDevice,
  SCREEN_SIZE_BREAKPOINT,
  DEFAULT_MEETING_ROOM,
  MEETING_CONSTRAINTS,
  PRIORITY_COLORS,
  DEFAULT_MEETING_SETTINGS,
  QUICK_MESSAGES,
  AVATAR_COLORS,
  ANIMATION_DURATION,
  CONTROLS_HIDE_TIMEOUT,
} from './common';
