import {StyleSheet, Dimensions} from 'react-native';

const {width: SCREEN_WIDTH, height: SCREEN_HEIGHT} = Dimensions.get('window');

export const createStyles = (isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: isDark ? '#121212' : '#f5f5f5',
    },
    headerContainer: {
      backgroundColor: isDark ? '#1a1a1a' : 'white',
      paddingVertical: 16,
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      elevation: 3,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.1,
      shadowRadius: 3,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: isDark ? 'white' : '#333',
    },
    backButton: {
      padding: 8,
    },
    refreshButton: {
      padding: 8,
      marginLeft: 'auto',
    },
    content: {
      flex: 1,
      padding: 16,
    },
    filterContainer: {
      flexDirection: 'row',
      marginBottom: 16,
      marginTop: 16,
      paddingHorizontal: 16,
    },
    filterButton: {
      marginRight: 12,
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 20,
      backgroundColor: isDark ? '#2a2a2a' : '#fff',
      borderWidth: 1,
      borderColor: isDark ? '#444' : '#e0e0e0',
    },
    filterButtonActive: {
      backgroundColor: '#2379C2',
      borderColor: '#2379C2',
    },
    filterText: {
      fontSize: 14,
      color: isDark ? '#e0e0e0' : '#555',
    },
    filterTextActive: {
      color: 'white',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    errorText: {
      fontSize: 16,
      color: isDark ? '#e0e0e0' : '#555',
      textAlign: 'center',
      marginBottom: 16,
    },
    retryButton: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      backgroundColor: '#2379C2',
      borderRadius: 8,
    },
    retryButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '500',
    },
    listItem: {
      backgroundColor: isDark ? '#2a2a2a' : 'white',
      borderRadius: 12,
      marginBottom: 16,
      overflow: 'hidden',
      flexDirection: 'row',
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.1,
      shadowRadius: 2,
    },
    eventImage: {
      width: '100%',
      height: SCREEN_WIDTH * 0.4,
      resizeMode: 'cover',
    },
    eventLogoContainer: {
      width: 100,
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: isDark ? '#1e1e1e' : '#f5f5f5',
      padding: 10,
    },
    eventInfo: {
      flex: 1,
      padding: 16,
    },
    eventTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: isDark ? 'white' : '#333',
      marginBottom: 8,
    },
    eventDescription: {
      fontSize: 14,
      color: isDark ? '#bbb' : '#666',
      marginBottom: 12,
    },
    eventDetailsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    eventDetailsText: {
      fontSize: 13,
      color: isDark ? '#ddd' : '#555',
      marginLeft: 8,
    },
    eventTag: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 4,
      paddingHorizontal: 10,
      backgroundColor: isDark ? '#444' : '#f0f0f0',
      borderRadius: 16,
      marginRight: 8,
      marginBottom: 8,
    },
    eventTagText: {
      fontSize: 12,
      color: isDark ? '#ddd' : '#555',
      marginLeft: 4,
    },
    tagsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 8,
    },
    footerButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 12,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: isDark ? '#444' : '#eee',
    },
    footerButton: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 8,
    },
    footerButtonText: {
      fontSize: 14,
      color: '#2379C2',
      marginTop: 4,
    },
    detailButtonContainer: {
      marginTop: 16,
    },
    detailButton: {
      backgroundColor: '#2379C2',
      paddingVertical: 10,
      borderRadius: 8,
      alignItems: 'center',
    },
    detailButtonText: {
      color: 'white',
      fontWeight: '500',
      fontSize: 16,
    },
    noEventsContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    noEventsText: {
      fontSize: 16,
      color: isDark ? '#e0e0e0' : '#555',
      textAlign: 'center',
      marginBottom: 16,
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      padding: 20,
    },
    modalContent: {
      backgroundColor: isDark ? '#1a1a1a' : 'white',
      borderRadius: 12,
      padding: 20,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: isDark ? 'white' : '#333',
      marginBottom: 16,
    },
    locationItem: {
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? '#444' : '#eee',
    },
    locationText: {
      fontSize: 16,
      color: isDark ? '#e0e0e0' : '#333',
    },
    closeButton: {
      marginTop: 16,
      alignItems: 'center',
      paddingVertical: 12,
      backgroundColor: '#2379C2',
      borderRadius: 8,
    },
    closeButtonText: {
      color: 'white',
      fontSize: 16,
      fontWeight: '500',
    },
    locationButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: isDark ? '#2a2a2a' : 'white',
      paddingVertical: 10,
      paddingHorizontal: 16,
      marginHorizontal: 16,
      marginTop: 16,
      borderRadius: 8,
      elevation: 1,
      shadowColor: '#000',
    },
    locationButtonText: {
      fontSize: 15,
      color: isDark ? 'white' : '#333',
    },
    eventCard: {
      backgroundColor: isDark ? '#2a2a2a' : 'white',
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      elevation: 2,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 1},
      shadowOpacity: 0.2,
      shadowRadius: 2,
      width: '100%',
    },
    darkEventCard: {
      backgroundColor: '#2a2a2a',
    },
    eventHeader: {
      flexDirection: 'row',
      marginBottom: 12,
      alignItems: 'center',
    },
    eventLogo: {
      width: 40,
      height: 40,
      borderRadius: 8,
      marginRight: 12,
    },
    fallbackLogoContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.2)',
    },
    eventHeaderText: {
      flex: 1,
    },
    darkText: {
      color: 'white',
    },
    darkSubText: {
      color: '#bbb',
    },
    eventDate: {
      fontSize: 13,
      color: '#666',
      marginBottom: 4,
    },
    eventFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 12,
    },
    locationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    eventLocation: {
      fontSize: 13,
      color: '#666',
      marginLeft: 4,
    },
    eventType: {
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: 16,
      backgroundColor: isDark ? '#333' : '#f0f0f0',
    },
    eventTypeText: {
      fontSize: 12,
      fontWeight: '500',
    },
    listContainer: {
      padding: 16,
      paddingBottom: 80,
    },
  });
